###################################################################################
# Wemos D1 mini https://www.wemos.cc/en/latest/_static/files/sch_d1_mini_v3.0.0.pdf
# https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/
###################################################################################
# D1 GPIO5 - TMC2208 DIR
# D2 GPIO4 - TMC2208 STEP
# D3 GPIO0 (pu, connected to FLASH button, boot fails if pulled LOW) - DEBUG: Toggle button
# D4 GPIO2 (pu, HIGH at boot, LED, boot fails if pulled LOW) - TMC2208 EN#
#
# D0 GPIO16 (HIGH at boot) - NC
# D5 GPIO14 - IR receiver
# D6 GPIO12 -Top endstop (reed switch).
# D7 GPIO13 - AM2301
# D8 GPIO15 (pd, Boot fails if pulled HIGH) - NC
#
# RX GPIO3 (HIGH at boot) - TMC TX
# TX GPIO1 (HIGH at boot, debug output at boot, boot fails if pulled LOW) - TMC RX
#
# TODO: BEEPER
# TODO: https://github.com/khoih-prog/ESP8266TimerInterrupt#12-set-hardware-timer-interval-and-attach-timer-interrupt-handler-function
#
# https://www.omc-stepperonline.com/support-stepper-motor/what-is-the-maximum-speed-highest-frequency-of-the-motor
#
# Nema 17:
#  	Max. Speed (RPM): 2000
#   Recommended. Working Speed (RPM): 200-600
#

esphome:
  name: rollerblinds
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: false
  includes:
    - stepper_cover.h
  libraries:
    - SPI
    - teemuatlut/TMCStepper
    - plerup/espsoftwareserial @ 6.8.5
    - khoih-prog/ESP8266TimerInterrupt @ 1.4.1

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: ""
      
ota:
  password: ""

wifi:
  <<: !include secrets/wifi.yaml

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "RollerBlinds"
    password: ""

captive_portal:

# AM2301
sensor:
  - platform: dht
    pin:
      number: D7
      mode: INPUT_PULLUP
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 5min

# Stepper
# ENN  - Enable not input. The power stage becomes switched off (all motor outputs floating) when this pin becomes driven to a high level.
# DIR  - DIR input (internal pull-down resistor)
# STEP - STEP input
#
# Timings:
# DIR -20ns-> STEP
# STEP -20ns-> DIR
# DIR -100ns-> !DIR
#
# Fastest mode: microstep = 1/2 step
# Fycetc TMC2208:
# MS1 - HIGH
# MS2 - LOW
#
 
cover:

  - platform: custom
    lambda: |-
      auto sc = new StepperCover();
      App.register_component(sc);
      return {sc};

    covers:
      - name: "Rollerblinds"
        id: rb

binary_sensor:
  - platform: remote_receiver
    id: remote_up
    lg:
      data: 0x00FF629D
      nbits: 32
    on_press:
      then:
        - cover.open: rb

  - platform: remote_receiver
    id: remote_down
    lg:
      data: 0x00FFA857
      nbits: 32
    on_press:
      then:
        - cover.close: rb

  - platform: gpio
    id: toggle_button
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: true # signaled state is when the button connect pin to the ground
    on_click:
    - min_length: 50ms
      max_length: 300ms
      then:
        - cover.open: rb
    - min_length: 300ms
      max_length: 1000ms
      then:
      - lambda: 'static_cast<StepperCover*>(rb)->settle();'

# вверх 0x00FF629D
# вниз  0x00FFA857
# ок    0x00FF02FD
# *     0x00FF42BD
# #     0x00FF52AD
remote_receiver:
  pin:
    number: D5
    inverted: True
    mode: INPUT_PULLUP
  dump: lg
