###################################################################################
# Wemos D1 mini https://www.wemos.cc/en/latest/_static/files/sch_d1_mini_v3.0.0.pdf
# https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/
###################################################################################
# D1 GPIO5 - TMC2208 DIR
# D2 GPIO4 - TMC2208 STEP
# D3 GPIO0 (pu, connected to FLASH button, boot fails if pulled LOW) - NC (devkit: Toggle button)
# D4 GPIO2 (pu, HIGH at boot, LED, boot fails if pulled LOW) - TMC2208 EN#
#
# D0 GPIO16 (HIGH at boot) - AUX-SQUARE NC
# D5 GPIO14 - AUX-ROUND Top endstop (reed switch)
# D6 GPIO12 - IR receiver 
# D7 GPIO13 - NC (devkit: AM2301)
# D8 GPIO15 (pd, Boot fails if pulled HIGH) - NC
#
# RX GPIO3 (HIGH at boot) - NC
# TX GPIO1 (HIGH at boot, debug output at boot, boot fails if pulled LOW) <-> R1K <-> TMC RX
#
# TODO: BEEPER
# TODO: https://github.com/khoih-prog/ESP8266TimerInterrupt#12-set-hardware-timer-interval-and-attach-timer-interrupt-handler-function
#
# https://www.omc-stepperonline.com/support-stepper-motor/what-is-the-maximum-speed-highest-frequency-of-the-motor
#
# Nema 17:
#  	Max. Speed (RPM): 2000
#   Recommended. Working Speed (RPM): 200-600
#

esphome:
  name: shutter
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: false
  includes:
    - stepper_cover.h
  libraries:
    - SPI
    - teemuatlut/TMCStepper
    - khoih-prog/ESP8266TimerInterrupt @ 1.6.0

# Enable logging
logger:
  level: DEBUG
  baud_rate: 115200

# Enable Home Assistant API
api:
  password: ""
      
ota:
  password: ""

wifi:
  <<: !include secrets/wifi.yaml

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "RollerBlinds"
    password: ""

captive_portal:

remote_receiver:
  pin:
    number: D6
    inverted: True
    mode: INPUT_PULLUP
  dump: lg

binary_sensor:
  - platform: remote_receiver
    id: remote_up
    lg:
      data: 0x00FF629D
      nbits: 32
    on_press:
      then:
        - cover.open: rb

  - platform: remote_receiver
    id: remote_down
    lg:
      data: 0x00FFA857
      nbits: 32
    on_press:
      then:
        - cover.close: rb

  - platform: remote_receiver
    id: remote_ok
    lg:
      data: 0x00FF02FD
      nbits: 32
    on_press:
      then:
        - if:
            condition:
              lambda: 'return id(rb).current_operation == CoverOperation::COVER_OPERATION_IDLE;'
            then:
              - cover.toggle: rb
            else:
              - cover.stop: rb
  
  - platform: remote_receiver
    id: remote_left
    lg:
      data: 0x00FF22DD
      nbits: 32
    on_press: 
      - homeassistant.tag_scanned: keyes-left

  - platform: remote_receiver
    id: remote_right
    lg:
      data: 0x00FFC23D
      nbits: 32
    on_press: 
      - homeassistant.tag_scanned: keyes-right

  - platform: remote_receiver
    id: remote_1
    lg:
      data: 0x00FF6897
      nbits: 32
    on_press: 
      - homeassistant.tag_scanned: keyes-1

  - platform: remote_receiver
    id: remote_2
    lg:
      data: 0x00FF9867
      nbits: 32
    on_press: 
      - homeassistant.tag_scanned: keyes-2

  - platform: remote_receiver
    id: remote_3
    lg:
      data: 0x00FFB04F
      nbits: 32
    on_press: 
      - homeassistant.tag_scanned: keyes-3

  - platform: remote_receiver
    id: remote_4
    lg:
      data: 0x00FF30CF
      nbits: 32
    on_press: 
      - homeassistant.tag_scanned: keyes-4

  - platform: remote_receiver
    id: remote_5
    lg:
      data: 0x00FF18E7
      nbits: 32
    on_press: 
      - homeassistant.tag_scanned: keyes-5

  - platform: remote_receiver
    id: remote_6
    lg:
      data: 0x00FF7A85
      nbits: 32
    on_press: 
      - homeassistant.tag_scanned: keyes-6

  - platform: remote_receiver
    id: remote_7
    lg:
      data: 0x00FF10EF
      nbits: 32
    on_press: 
      - homeassistant.tag_scanned: keyes-7

  - platform: remote_receiver
    id: remote_8
    lg:
      data: 0x00FF38C7
      nbits: 32
    on_press: 
      - homeassistant.tag_scanned: keyes-8

  - platform: remote_receiver
    id: remote_9
    lg:
      data: 0x00FF5AA5
      nbits: 32
    on_press: 
      - homeassistant.tag_scanned: keyes-9

  - platform: remote_receiver
    id: remote_0
    lg:
      data: 0x00FF4AB5
      nbits: 32
    on_press: 
      - homeassistant.tag_scanned: keyes-0

  - platform: remote_receiver
    id: remote_asterisk
    lg:
      data: 0x00FF42BD
      nbits: 32
    on_press: 
      - homeassistant.tag_scanned: keyes-asterisk

  - platform: remote_receiver
    id: remote_hash
    lg:
      data: 0x00FF52AD
      nbits: 32
    on_press: 
      - homeassistant.tag_scanned: keyes-hash
  

cover:

  - platform: custom
    lambda: |-
      auto sc = new StepperCover();
      App.register_component(sc);
      return {sc};

    covers:
      - name: "Rollerblinds"
        id: rb


  # - platform: gpio
  #   id: toggle_button
  #   pin:
  #     number: D3
  #     mode: INPUT_PULLUP
  #     inverted: true # signaled state is when the button connect pin to the ground
  #   on_click:
  #   - min_length: 50ms
  #     max_length: 300ms
  #     then:
  #       - cover.open: rb
  #   - min_length: 300ms
  #     max_length: 1000ms
  #     then:
  #     - lambda: 'static_cast<StepperCover*>(rb)->settle();'

# AM2301
# sensor:
#   - platform: dht
#     pin:
#       number: D7
#       mode: INPUT_PULLUP
#     temperature:
#       name: "Living Room Temperature"
#     humidity:
#       name: "Living Room Humidity"
#     update_interval: 5min

# Stepper
# ENN  - Enable not input. The power stage becomes switched off (all motor outputs floating) when this pin becomes driven to a high level.
# DIR  - DIR input (internal pull-down resistor)
# STEP - STEP input
#
# Timings:
# DIR -20ns-> STEP
# STEP -20ns-> DIR
# DIR -100ns-> !DIR
#
# Fastest mode: microstep = 1/2 step
# Fycetc TMC2208:
# MS1 - HIGH
# MS2 - LOW
#
 

# вверх 0x00FF629D
# вниз  0x00FFA857
# ок    0x00FF02FD
# *     0x00FF42BD
# #     0x00FF52AD
