#!/usr/bin/env python3

from cProfile import label
import numpy as np
import matplotlib.pyplot as plt

# time_rst = (
# 	()
# )

reset_start = 50

def rts(t):
	t = t % 1000
	if t < reset_start: return 1
	if t <= (reset_start + 100): return 0
	return 1
rts = np.frompyfunc(rts, 1, 1)

def dtr(t):
	t = t % 1000
	if t <= (reset_start + 100): return 1
	if t <= (reset_start + 150): return 0
	return 1
dtr = np.frompyfunc(dtr, 1, 1)

def reset(t):
	if dtr(t) and not rts(t): return 0
	return 1
reset = np.frompyfunc(reset, 1, 1)

def flash(t):
	if rts(t) and not dtr(t): return 0
	return 1
flash = np.frompyfunc(flash, 1, 1)

t = np.arange(0, 500, 10)

fig, axs = plt.subplots(2)
fig.suptitle('ESP8266 RESET CYCLE TO FLASHING')

axs[0].plot(t, rts(t), label = 'RTS')
axs[0].plot(t, dtr(t), label = 'DTR')
axs[0].legend()

axs[1].plot(t, reset(t), label = 'RESET')
axs[1].plot(t, flash(t), label = 'FLASH')
axs[1].legend()

plt.show()
